### ISSUE TITLE
Betterhud-mmocore and mmoitem conflict

### ISSUE THREAD

**Issue by gfdugfj** [toxicity188/BetterHud-MMOCore#1]
Today I discovered something when I was modifying the mmoitem version. Why does BetterHudMMOCore conflict with mmoitem?
Why did I find out? Because I accidentally updated Mmoitem to the new version. As a result, mmoitem stopped working. Then I found that BetterHudMMOCore actually worked normally.

To put it simply, BetterHudMMOCore conflicts with mmoitem
when mmoitem It's broken while it's there

**Comment by toxicity188** [comment]
No log or screenshot; i can't provide any help to you.
