### ISSUE TITLE
 BetterHudMMOCore conflicts with mmoitem when mmoitem It's broken while it's there

### ISSUE THREAD

**Issue by gfdugfj** [toxicity188/BetterHud-MMOCore#2]
![1](https://github.com/user-attachments/assets/47295626-c137-49f3-803a-ddaa165df4b6)
The picture above is the error message after loading mmoitem. 

![image](https://github.com/user-attachments/assets/00d3fe9e-c332-4e5c-90a2-1172dbea86ae)
![3](https://github.com/user-attachments/assets/2531b834-437b-4be4-bab9-5c5e36ee16c3)
The above is the normal operation of betterhud-mmocore after removing mmoitem.

Server version: 1.20.1
paper
Various plugins versions
MythicLib-1.6.1 MMOCore-1.12 BetterHud-1.6.246 BetterHud-MMOCore-1.4 PlaceholderAPI-2.11.6 MMOItems-6.9.5

**Comment by toxicity188** [comment]
Your MythicLib version issue.
